kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nanobot
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /mnt/d/codes/nanobot_modify/nanobot/host_test_env
        containerPath: /mnt/env
      - hostPath: /mnt/d/codes/nanobot_modify/nanobot
        containerPath: /mnt/source
