apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/env
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-data-pvc
  namespace: nanobot
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: nanobot-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-source-pv
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/source
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-source-pvc
  namespace: nanobot
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  volumeName: nanobot-source-pv
