apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-source-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.30.100
    path: /data/nanobot-nfs/source
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-source-pvc
  namespace: nanobot
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nanobot-source-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-common-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.30.100
    path: /data/nanobot-nfs/common
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-common-pvc
  namespace: nanobot
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  volumeName: nanobot-common-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-frontends-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.30.100
    path: /data/nanobot-nfs/frontends
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-frontends-pvc
  namespace: nanobot
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nanobot-frontends-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-workspaces-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.30.100
    path: /data/nanobot-nfs/workspaces
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-workspaces-pvc
  namespace: nanobot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: nanobot-workspaces-pv
