apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-data-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.30.100
    path: /data/nanobot-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-data-pvc
  namespace: nanobot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: nanobot-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-source-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.30.100
    path: /data/nanobot-source
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-source-pvc
  namespace: nanobot
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  volumeName: nanobot-source-pv
