apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/env
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-data-pvc
  namespace: nanobot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nanobot-source-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/source
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nanobot-source-pvc
  namespace: nanobot
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
